services:
  server:
    environment:
      - config_path=/var/service_config/config.yaml
    build:
      context: .
      target: final
    ports:
      - 8888:8888
    depends_on:
       db:
         condition: service_healthy
       nats:
         condition: service_started
  db:
   image: postgres
   restart: always
   volumes:
     - db:/var/lib/postgresql/data
     - ./db:/docker-entrypoint-initdb.d
   environment:
     - POSTGRES_DB=postgres
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=liza
     - PGUSER=postgres
   expose:
     - 5432
   healthcheck:
     test: [ "CMD", "pg_isready"]
     interval: 5s
     timeout: 5s
     retries: 5

  nats:
    image: nats
    ports:
      - "8222:8222"
    command: "--data NATS --cluster nats://0.0.0.0:6222 --http_port 8222 "
volumes:
  db:
    driver: local
#secrets:
#  db-password:
#    file: db/password.txt

