db:
  db_user: "postgres"
  db_pass: "liza"
  db_name: "Support"
server:
  ssl_mode: "disable"
  timeout: 10s
  idle_timeout: 30s
  address: "0.0.0.0:8888"
nats:
  address: "nats://localhost:8887"
  retry: Yes
  max_reconnects: 10
  reconnect_wait: 10s
